### ISSUE TITLE
分段的逻辑有点小问题

### ISSUE THREAD

**Issue by IlluminateDarkheat** [IndieKKY/bilibili-subtitle#1]
建议改为比 4000 略小的数值，防止这种情况出现
[视频链接](https://www.bilibili.com/video/BV1ic411P7Tm)

![image](https://github.com/IndieKKY/bilibili-subtitle/assets/28666767/6b53586e-80d3-4869-b726-627081ba4081)

**Comment by IndieKKY** [comment]
设置里分段字数是不选的3000？这个概览的总结因为会传时间戳，因此传入的token的确会多一些，分段字段要选2000才安全。
这一块后续会想办法优化。

**Comment by IlluminateDarkheat** [comment]
刚开始用，还是默认的2000

**Comment by IlluminateDarkheat** [comment]
这个视频里分出的第二段，在文章视图中看到的段落刚好2002个中文字符，会不会是直接把中文字符当成 token 判断了？

![image](https://github.com/IndieKKY/bilibili-subtitle/assets/28666767/bbd7b53a-9426-4fd7-9dd1-8736a3655c65)

**Comment by IndieKKY** [comment]
> 这个视频里分出的第二段，在文章视图中看到的段落刚好2002个中文字符，会不会是直接把中文字符当成 token 判断了？
> 
> ![image](https://user-images.githubusercontent.com/28666767/239159879-bbd7b53a-9426-4fd7-9dd1-8736a3655c65.png)

是的，目前凑合用用，后面会优化。

**Comment by IlluminateDarkheat** [comment]
好的，期待☺️
