### ISSUE TITLE
非常好用的插件，不知未來是否會添加一件總結所有內容

### ISSUE THREAD

**Issue by poposhi** [IndieKKY/bilibili-subtitle#10]
目前一次只能大約總結7分鐘到10分鐘，如果要總結其他段落需要捲動下去然後再按按鈕 ，另外想要請問總結內容是使用什麼樣子的提示詞，我自己請語言模型幫忙總結的時候總是不太穩定

**Comment by IndieKKY** [comment]
可以批量总结
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/121992849/788c56ce-a50c-4de9-a55d-d885b5d0cd10)

**Comment by IndieKKY** [comment]
提示词也可以在设置里修改
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/121992849/a458638e-4564-47ae-bcaa-12c0bf72c946)

**Comment by IndieKKY** [comment]
提示词内容例子我后续补充上

**Comment by poposhi** [comment]
了解，非常感謝您
