### ISSUE TITLE
希望增加模型选择

### ISSUE THREAD

**Issue by chenqianhe** [IndieKKY/bilibili-subtitle#11]
目前 openai 对模型进行了更新，希望可以增加选择模型的设置

https://github.com/IndieKKY/bilibili-subtitle/blob/8c8d5bf4e14111c2d90520f687ef2343bd83476d/src/chrome/openaiService.ts#L6

**Comment by IndieKKY** [comment]
好的

**Comment by IndieKKY** [comment]
新版本已增加
