### ISSUE TITLE
使用 HEVC 解码时 Chrome 浏览器不支持跳转视频

### ISSUE THREAD

**Issue by nuzar** [IndieKKY/bilibili-subtitle#13]
插件提示
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/4602400/db9e5cb2-0d0f-4ed0-9f77-24216ee69a1f)

我记得以前是能跳转的，是我记错了吗？还是有什么调整？

**Comment by IndieKKY** [comment]
chrome可以跳转的，测试mac下edge浏览器是不能跳转，因此加了这个提示。
可以重新打开浏览器看看，最近插件并没有改动，如果有变化，应该是b站或浏览器更新了。

**Comment by nuzar** [comment]
> chrome可以跳转的，测试mac下edge浏览器是不能跳转，因此加了这个提示。 可以重新打开浏览器看看，最近插件并没有改动，如果有变化，应该是b站或浏览器更新了。

看了下代码判断逻辑是
```
const getVideoElement = () => {
  const videoWrapper = document.getElementById('bilibili-player')
  return videoWrapper.querySelector('video')
}
```


在B站网页上没找到`video`这个元素，但是有个`bwp-video`
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/4602400/598ef1dd-1e9d-4160-a34c-f0fadabbf7c2)

**Comment by nuzar** [comment]
我的浏览器支持hevc解码，默认状态下找不到`video`，只有`bwp-video`。如果手动选择avc解码，就能找到`video`。

**Comment by nuzar** [comment]
尝试修改插件未成功，相关issuse:
https://github.com/the1812/Bilibili-Evolved/issues/2544

**Comment by IndieKKY** [comment]
对的，这个问题目前没找到好的办法

**Comment by nuzar** [comment]
这篇文章看起来可行，晚上我试一下
https://my.oschina.net/u/1165423/blog/5509674

**Comment by IndieKKY** [comment]
正准备研究解决，可能是edge或b站更新了，现在mac的edge里又能正常跳转了，因此暂时未找到方式复现此问题，只能先缓缓。

**Comment by nuzar** [comment]
重新测试了 av1, avc, hevc 的播放页面，时间调整功能正常，原因不详🤦‍♂️
