### ISSUE TITLE
not translating to english?

### ISSUE THREAD

**Issue by wawaawawa** [IndieKKY/bilibili-subtitle#16]
<img width="367" alt="Screenshot 2023-08-08 at 10 45 28 PM" src="https://github.com/IndieKKY/bilibili-subtitle/assets/141802568/5384d581-09ee-46f7-94da-44b20d44a747">

<img width="348" alt="Screenshot 2023-08-08 at 10 45 38 PM" src="https://github.com/IndieKKY/bilibili-subtitle/assets/141802568/e445c078-fca8-4b28-9442-1c1609ace086">

i'm english and this seems very useful for me but it doesn't want to translate to english and the interface isn't translated so i'm not sure how to fix this

**Comment by IndieKKY** [comment]
It use openai to translate, you need set ApiKey first.

**Comment by wawaawawa** [comment]
hmm okay, it seems i do not have sufficient usage rates in the free version of open ai, is this the problem?

**Comment by IndieKKY** [comment]
yes, free openai account has api request rate limit.

**Comment by wawaawawa** [comment]
okay thank you for quick response :)

**Comment by IndieKKY** [comment]
You're welcome
