### ISSUE TITLE
请问能否添加一个一键复制字幕的功能

### ISSUE THREAD

**Issue by Chenm4** [IndieKKY/bilibili-subtitle#19]
有时候想要保存字幕只能先下载，感觉还是麻烦了，能否添加一个一键复制字幕到剪切板的功能（复制的内容不包括换行符）？或者能否修改下让在article view界面直接鼠标选中字幕复制能够不复制到换行符（还有会复制到中间的key points等字，能否也去除掉）感谢感谢！
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/98648589/28e81a92-73d3-4343-b86b-7c1cfe636a1e)

**Comment by IndieKKY** [comment]
<img width="362" alt="image" src="https://github.com/IndieKKY/bilibili-subtitle/assets/121992849/90dfa09b-e4b9-4bef-a975-3102e4f18aa2">
下载选项上方不是有复制选项吗?

**Comment by Chenm4** [comment]
噢噢我发现b站是有的但是YouTube的插件没有这个功能，能给油管插件也添加一下吗，感谢感谢！（同时想问下油管的插件代码开源了吗我想以后有空可以学习修改下）

**Comment by IndieKKY** [comment]
youtube这个插件后面打算重构,到时会有这个功能
