### ISSUE TITLE
在部分分p视频中只能生成1p的字幕，其他几p好像都无法生成呀

### ISSUE THREAD

**Issue by yuha0lin** [IndieKKY/bilibili-subtitle#20]

**Comment by yuha0lin** [comment]
https://www.bilibili.com/video/BV15w411Z7LG?p=1&vd_source=377c4c54d25ee381d18efea1ba4427ab
我是用这个视频做的测试，求助大佬

**Comment by IndieKKY** [comment]
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/121992849/1c2fb30a-ebff-4765-b20c-4ef4f027af68)
视频本身没有自带字幕

**Comment by yuha0lin** [comment]
感谢大佬，我以为是自动生成的
