### ISSUE TITLE
可以改一下主色调吗？深色模式下（高亮）字体不够清晰

### ISSUE THREAD

**Issue by bowencool** [IndieKKY/bilibili-subtitle#22]
<img width="439" alt="图片" src="https://github.com/IndieKKY/bilibili-subtitle/assets/20217146/df3d3b03-b067-4a27-a571-6267f890b3d4">

我个人是比较倾向于使用与 B 站相同的主色

**Comment by IndieKKY** [comment]
请问b站的深色模式是怎么打开的，是哪个扩展的功能？

**Comment by bowencool** [comment]
> 请问b站的深色模式是怎么打开的，是哪个扩展的功能？

这个：https://chromewebstore.google.com/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh
但实际上它并不能更改另一个扩展的页面，关掉也是一样的
<img width="393" alt="image" src="https://github.com/IndieKKY/bilibili-subtitle/assets/20217146/3f9076b1-756c-426f-b75c-8064e7895461">

**Comment by IndieKKY** [comment]
好的

**Comment by IndieKKY** [comment]
新版本已修改发布
