### ISSUE TITLE
希望增加个字幕的语言类型开关

### ISSUE THREAD

**Issue by ryuka11** [IndieKKY/bilibili-subtitle#30]
如果是英文的视频字幕，可以保持英文的，或者可以增加个开关是否保持为英文，或者可以选择翻译陈中文

**Comment by IndieKKY** [comment]
这个插件只能使用视频自带的字幕文件，有的视频可能英文字幕内嵌到视频里面，但并没有提供英文的字幕文件，尤其是很多英语学习类视频。

**Comment by ryuka11** [comment]
哦，明白了，谢谢
