### ISSUE TITLE
[suggestion]本地openAI支持

### ISSUE THREAD

**Issue by STOI123** [IndieKKY/bilibili-subtitle#31]
目前会出现跨域问题. 已排除自己本地的部署的问题. 
https://medium.com/dcoderai/how-to-handle-cors-settings-in-ollama-a-comprehensive-guide-ee2a5a1beef0

await fetch(`${n}/v1/chat/completions`跨域
解决方案. https://stackoverflow.com/questions/77911717/issue-with-calling-a-local-ollama-api-from-chrome-extension

**Comment by IndieKKY** [comment]
新版本1.9.2已添加支持

**Comment by STOI123** [comment]
edge store咋没更新的, chrome store版本高于edge好几版

**Comment by STOI123** [comment]
试了, 可以正常运行. 赞
