### ISSUE TITLE
无法显示字幕提取页面

### ISSUE THREAD

**Issue by DateBender** [IndieKKY/bilibili-subtitle#38]
![image](https://github.com/user-attachments/assets/b37565c1-bb39-4168-869a-c48198a062c8)

**Comment by DateBender** [comment]
![image](https://github.com/user-attachments/assets/f90dbfc9-6e6e-4116-a3eb-7312694060d7)

**Comment by IndieKKY** [comment]
有时会加载不出，一般刷新下网页就好
