### ISSUE TITLE
可以在Linux下批量实现吗？

### ISSUE THREAD

**Issue by xyx361100238** [IndieKKY/bilibili-subtitle#4]
如题，是否可以在linux下实现批量的字幕转写和下载？

**Comment by xyx361100238** [comment]
你的这个字幕是获取了官方提供的字幕文字吗？

**Comment by IndieKKY** [comment]
是的

**Comment by IndieKKY** [comment]
可以看content-script.cjs文件

**Comment by xyx361100238** [comment]
多谢，我学习下

**Comment by xyx361100238** [comment]
我仿照fetch方法，用python请求url有内容返回，但是关键信息data.subtitle.list内容是空的   你在请求前是有什么认证之类的吗？

**Comment by xyx361100238** [comment]
补充一下：我直接网页访问的内容也是正常的
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/19569322/7bc85e29-d360-4534-8445-15069a2874d3)

用python返回：
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/19569322/22a0ea29-84df-44fd-8b67-cb82952a48cd)

**Comment by IndieKKY** [comment]
b站后面加了认证，要登录账号，传相应cookie进去才能拿到。
