### ISSUE TITLE
 Content Security Policy 出错

### ISSUE THREAD

**Issue by Spencer6-7** [IndieKKY/bilibili-subtitle#49]
content-script-loade…31cff.5242974d.js:7 Refused to load the script 'chrome-extension://8ac07a63-7e05-4ac3-8ba2-7e0d15f84cc4/assets/inject.ts.f2831cff.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

TypeError: Failed to fetch dynamically imported module: chrome-extension://8ac07a63-7e05-4ac3-8ba2-7e0d15f84cc4/assets/inject.ts.f2831cff.js

chrome浏览器出错，报错如上。edge浏览器没问题。

**Comment by IndieKKY** [comment]
已修复，提交审核了
