### ISSUE TITLE
无法翻译，求助！

### ISSUE THREAD

**Issue by ruhchjdbdbhccjjc** [IndieKKY/bilibili-subtitle#57]
<img width="553" alt="Snipaste_2024-12-07_00-00-09" src="https://github.com/user-attachments/assets/5037e013-7634-4dd2-8b48-ebe55730e37e">

**Comment by IndieKKY** [comment]
翻译条数可以改小点试试，调用ai翻译的，可能比较慢，条数改小会快些。

**Comment by ruhchjdbdbhccjjc** [comment]
谢谢。是正确的解决方案。
