### ISSUE TITLE
部分视频显示未找到字幕

### ISSUE THREAD

**Issue by yukun80** [IndieKKY/bilibili-subtitle#8]
请问这个扩展的实现是通过爬虫还是openai的语音识别呢?有些视频我发现提示没有找到字幕,看到设置里面有openai的配置,请问是可以通过api自动生成字幕吗?

**Comment by IndieKKY** [comment]
字幕是获取视频自带的字幕文件，并非生成的。

**Comment by jdukwjdo** [comment]
原视频有字幕的也没有获取到啊，https://www.bilibili.com/video/BV1bX4y1y7un/?spm_id_from=333.1007.tianma.1-2-2.click&vd_source=74bed6b6079b76b17754960988ca54b8
![image](https://github.com/IndieKKY/bilibili-subtitle/assets/11895200/858227cc-6cc1-4ecb-9af5-f103d1c71db0)

**Comment by IndieKKY** [comment]
这是内嵌到视频里的，没有外挂的字幕文件，具体可参考：
![20230525090045](https://github.com/IndieKKY/bilibili-subtitle/assets/121992849/f03e24d6-ffc7-4a27-891e-898f7717fd2a)
